### ISSUE TITLE
Attempt to invoke interface method

### ISSUE THREAD

**Issue by ramonjobsity** [AgoraIO/React-Native-SDK#24]
![Screenshot_20190316-164858_Telemedico Doctor](https://user-images.githubusercontent.com/16671164/54482070-aa450180-480b-11e9-9d9b-648a5f738f57.jpg)

**Comment by plutoless** [comment]
please refer to this repo if you are having problems using this one, https://github.com/AgoraIO-Community/Agora-RN-Quickstart
This repo is about to be deprecated.
