### ISSUE TITLE
android build报错

### ISSUE THREAD

**Issue by Evangelione** [AgoraIO/React-Native-SDK#3]
错误: 方法不会覆盖或实现超类型的方法

错误: 找不到符号
符号:   方法 setSpeakerphoneVolume(int)
位置: 类型为RtcEngine的变量 mRtcEngine

错误: 找不到符号
符号:   方法 monitorConnectionEvent(boolean)
位置: 类型为RtcEngine的变量 mRtcEngine

**Comment by Evangelione** [comment]
声网不打算做react-native版的sdk吗

**Comment by Evangelione** [comment]
错误: 找不到或无法加载主类 org.gradle.wrapper.GradleWrapperMain

**Comment by cmder** [comment]
> 错误: 找不到或无法加载主类 org.gradle.wrapper.GradleWrapperMain

copy android/gradle/wrapper/gradle-wrapper.jar to the same location from other projects

**Comment by cmder** [comment]
> 错误: 方法不会覆盖或实现超类型的方法
> 
> 错误: 找不到符号
> 符号: 方法 setSpeakerphoneVolume(int)
> 位置: 类型为RtcEngine的变量 mRtcEngine
> 
> 错误: 找不到符号
> 符号: 方法 monitorConnectionEvent(boolean)
> 位置: 类型为RtcEngine的变量 mRtcEngine

the two methods have been deprecated in our latest sdk, please delete them from AgoraModule.java by yourself.

**Comment by PRWrl** [comment]
https://github.com/AgoraIO/React-Native-SDK/commit/d5c3f88b6a824446ea66348c6c17128003eb90b4
