### ISSUE TITLE
error: cannot find symbol method setSpeakerphoneVolume(int)

### ISSUE THREAD

**Issue by dyegooviedo** [AgoraIO/React-Native-SDK#4]
Java compiler errors
error: cannot find symbol method setSpeakerphoneVolume(int)

error: cannot find symbol method monitorConnectionEvent(boolean)

/Projetos/Agora/android/app/src/main/java/com/rnapi/AgoraModule.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

Can anybody help me?

**Comment by cmder** [comment]
> setSpeakerphoneVolume(int)

the two methods have been deprecated in our latest sdk, please delete them from AgoraModule.java by yourself.

**Comment by PRWrl** [comment]
https://github.com/AgoraIO/React-Native-SDK/commit/d5c3f88b6a824446ea66348c6c17128003eb90b4
