### ISSUE TITLE
Can't install in react-native-0.57 (Android)

### ISSUE THREAD

**Issue by waldiirawan** [AgoraIO/React-Native-SDK#8]
## Environment
System:
      OS: macOS 10.14.1
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 45.25 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
      Yarn: 1.5.1 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4697961
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1

## Description
I created a new project with "create-react-native-app" and I follow the instruction as well, but I got an error when I open your example page

<img width="306" alt="screen shot 2018-10-11 at 19 02 50" src="https://user-images.githubusercontent.com/10203954/46802734-634c6f00-cd88-11e8-968f-f0ab0def0390.png">

**Comment by cmder** [comment]
You put the .so file in the wrong place, please fix it.

**Comment by waldiirawan** [comment]
Can you tell me where is the right place?

**Comment by waldiirawan** [comment]
I successfully start the app when I set "targetSdkVersion 22" but error when I changed the target SDK to 25.
I think this issue related to this link https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#text-relocations-enforced-for-api-level-23

<img width="306" alt="screen shot 2018-10-11 at 19 02 50" src="https://user-images.githubusercontent.com/10203954/46865913-78d59d80-ce49-11e8-9adb-57bc21f23836.png">

**Comment by waldiirawan** [comment]
what should I do? @cmder

**Comment by cmder** [comment]
> Can you tell me where is the right place?

please put them in folder 'src/main/jniLibs'

**Comment by plutoless** [comment]
closed due to inactivity for more than 1 month
